name: Generate Snake

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Generate snake
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: vireakech6724
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # 3️⃣ Commit and push safely
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p dist
          git add dist/
          git commit -m "update snake" || echo "no changes"

          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vireakech6724/vireakech6724.git main
